name: Update README

on:
  schedule:
    - cron: "* */12 * * *" # Cada 12 horas
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README 
    steps:
      - uses: actions/checkout@v2
      - uses: Deigowo/recent-activity@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
